// Package kube builds Kubernetes clients and collects typed diagnostic snapshots.
package kube

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/kmizuki03/k8s-diagnose/internal/config"
	"github.com/kmizuki03/k8s-diagnose/internal/redact"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

type ErrorStatus string

const (
	StatusOK           ErrorStatus = "ok"
	StatusNotFound     ErrorStatus = "notfound"
	StatusForbidden    ErrorStatus = "forbidden"
	StatusUnauthorized ErrorStatus = "unauthorized"
	StatusTimeout      ErrorStatus = "timeout"
	StatusUnavailable  ErrorStatus = "unavailable"
	StatusInvalid      ErrorStatus = "invalid"
	StatusError        ErrorStatus = "error"
)

type Clients struct {
	Kube       kubernetes.Interface
	Dynamic    dynamic.Interface
	Discovery  discovery.DiscoveryInterface
	RESTConfig *rest.Config
	Context    string
	Namespace  string
	Timeout    time.Duration
	warnings   *warningRecorder
	trace      *requestTracer
}

type warningRecorder struct {
	mu     sync.Mutex
	values []string
}

type requestTracer struct {
	mu         sync.Mutex
	writer     io.Writer
	serverTime time.Time
}

func (t *requestTracer) setWriter(writer io.Writer) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.writer = writer
}

func (t *requestTracer) write(method, requestURI string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.writer != nil {
		// This trace is emitted only for text output. method and RequestURI are
		// generated by net/http/client-go (headers and bodies are never traced).
		fmt.Fprintf(t.writer, "    $ Kubernetes API %s %s\n", method, requestURI) // #nosec G705 -- terminal text, not an HTML sink.
	}
}

func (t *requestTracer) recordServerTime(value string) {
	parsed, err := http.ParseTime(value)
	if err != nil {
		return
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	if parsed.After(t.serverTime) {
		t.serverTime = parsed
	}
}

func (t *requestTracer) getServerTime() time.Time {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.serverTime
}

func (t *requestTracer) resetServerTime() {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.serverTime = time.Time{}
}

type tracingRoundTripper struct {
	base   http.RoundTripper
	tracer *requestTracer
}

func addRequestTracer(config *rest.Config, tracer *requestTracer) {
	config.Wrap(func(base http.RoundTripper) http.RoundTripper {
		return tracingRoundTripper{base: base, tracer: tracer}
	})
}

func (t tracingRoundTripper) RoundTrip(request *http.Request) (*http.Response, error) {
	t.tracer.write(request.Method, request.URL.RequestURI())
	response, err := t.base.RoundTrip(request)
	if response != nil {
		t.tracer.recordServerTime(response.Header.Get("Date"))
	}
	return response, err
}

func (r *warningRecorder) HandleWarningHeader(_ int, _ string, message string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	for _, value := range r.values {
		if value == message {
			return
		}
	}
	r.values = append(r.values, message)
}

func (r *warningRecorder) Drain() []string {
	r.mu.Lock()
	defer r.mu.Unlock()
	values := append([]string{}, r.values...)
	r.values = nil
	return values
}

func NewClients(cfg config.Config) (*Clients, error) {
	rules := clientcmd.NewDefaultClientConfigLoadingRules()
	if cfg.Kubeconfig != "" {
		path, err := filepath.Abs(cfg.Kubeconfig)
		if err != nil {
			return nil, fmt.Errorf("kubeconfigパスを解決できません: %w", err)
		}
		rules.ExplicitPath = path
	}
	overrides := &clientcmd.ConfigOverrides{CurrentContext: cfg.Context}
	deferred := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(rules, overrides)
	raw, err := deferred.RawConfig()
	if err != nil {
		return nil, fmt.Errorf("kubeconfigを読み込めません: %w", err)
	}
	contextName := raw.CurrentContext
	if cfg.Context != "" {
		contextName = cfg.Context
	}
	restConfig, err := deferred.ClientConfig()
	if err != nil {
		return nil, fmt.Errorf("Kubernetesクライアント設定を作成できません: %w", err)
	}
	restConfig = rest.CopyConfig(restConfig)
	restConfig.Timeout = time.Duration(cfg.RequestTimeout) * time.Second
	restConfig.QPS = float32(cfg.QPS)
	restConfig.Burst = cfg.Burst
	restConfig.UserAgent = fmt.Sprintf("k8s-diagnose/%s", config.Version)
	warnings := &warningRecorder{}
	tracer := &requestTracer{}
	restConfig.WarningHandler = warnings
	addRequestTracer(restConfig, tracer)
	kube, err := kubernetes.NewForConfig(restConfig)
	if err != nil {
		return nil, fmt.Errorf("Kubernetes typed clientを作成できません: %w", err)
	}
	dynamicClient, err := dynamic.NewForConfig(restConfig)
	if err != nil {
		return nil, fmt.Errorf("Kubernetes dynamic clientを作成できません: %w", err)
	}
	discoveryClient, err := discovery.NewDiscoveryClientForConfig(restConfig)
	if err != nil {
		return nil, fmt.Errorf("Kubernetes discovery clientを作成できません: %w", err)
	}
	return &Clients{Kube: kube, Dynamic: dynamicClient, Discovery: discoveryClient, RESTConfig: restConfig, Context: contextName, Namespace: cfg.Namespace, Timeout: restConfig.Timeout, warnings: warnings, trace: tracer}, nil
}

func (c *Clients) DrainWarnings() []string {
	if c == nil || c.warnings == nil {
		return nil
	}
	return c.warnings.Drain()
}

// BeginCollection resets request-scoped timing state while leaving Warning
// headers queued so warnings emitted by Preflight are included in the first
// collected snapshot. Warnings are drained when that snapshot is complete.
func (c *Clients) BeginCollection() {
	if c != nil && c.trace != nil {
		c.trace.resetServerTime()
	}
}

// SetTraceWriter enables a sanitized trace of the actual client-go HTTP
// requests. Authentication headers and request bodies are never printed.
func (c *Clients) SetTraceWriter(writer io.Writer) { c.trace.setWriter(writer) }

func (c *Clients) ServerTime() time.Time {
	if c == nil || c.trace == nil {
		return time.Time{}
	}
	return c.trace.getServerTime()
}

func ClassifyError(err error) ErrorStatus {
	if err == nil {
		return StatusOK
	}
	switch {
	case apierrors.IsNotFound(err):
		return StatusNotFound
	case apierrors.IsForbidden(err):
		return StatusForbidden
	case apierrors.IsUnauthorized(err):
		return StatusUnauthorized
	case apierrors.IsTimeout(err) || apierrors.IsServerTimeout(err):
		return StatusTimeout
	case apierrors.IsServiceUnavailable(err) || apierrors.IsTooManyRequests(err):
		return StatusUnavailable
	case apierrors.IsInvalid(err) || apierrors.IsBadRequest(err):
		return StatusInvalid
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return StatusTimeout
	}
	var netError interface{ Timeout() bool }
	if errors.As(err, &netError) && netError.Timeout() {
		return StatusTimeout
	}
	return StatusError
}

func HTTPStatusCode(err error) int32 {
	if err == nil {
		return 0
	}
	var status apierrors.APIStatus
	if errors.As(err, &status) {
		return status.Status().Code
	}
	return 0
}

func ErrorReason(err error) string {
	if err == nil {
		return ""
	}
	label := map[ErrorStatus]string{
		StatusNotFound: "対象が見つかりません", StatusForbidden: "アクセス権限がありません (RBAC)",
		StatusUnauthorized: "認証が必要です", StatusTimeout: "要求がタイムアウトしました",
		StatusUnavailable: "Kubernetes APIに到達できません", StatusInvalid: "API要求が不正です",
	}[ClassifyError(err)]
	detail := redact.MaskSecrets(strings.Join(strings.Fields(err.Error()), " "))
	detail = strings.TrimSpace(strings.TrimPrefix(detail, "error:"))
	if runes := []rune(detail); len(runes) > 300 {
		detail = string(runes[:300]) + "…"
	}
	if label == "" {
		return "Kubernetes APIでエラーが発生しました: " + detail
	}
	if detail == "" {
		return label
	}
	return label + ": " + detail
}

func (c *Clients) Preflight(ctx context.Context) error {
	namespace := c.Namespace
	_, err := c.Kube.CoreV1().Pods(namespace).List(ctx, listOptions(1, "metadata.name=__k8s_diagnose_preflight__"))
	if err != nil {
		if c.Namespace != "" && apierrors.IsNotFound(err) {
			return fmt.Errorf("Namespace %q が見つかりません", c.Namespace)
		}
		return fmt.Errorf("Kubernetesクラスタに接続できません。原因: %s", ErrorReason(err))
	}
	return nil
}

func HomeKubeconfig() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".kube", "config")
}
