// Package rbac generates least-privilege templates from the same rule
// metadata used for Coverage. This prevents diagnostics and documentation from
// silently drifting away from the required Kubernetes permissions.
package rbac

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/kmizuki03/k8s-diagnose/internal/report"
	"github.com/kmizuki03/k8s-diagnose/internal/rules"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/validation"
	"sigs.k8s.io/yaml"
)

const generatedHeader = "# Generated by go run ./cmd/rbac. Do not edit by hand.\n"

func Reader(clusterScoped bool, namespace string) any {
	kind := "Role"
	if clusterScoped {
		kind = "ClusterRole"
	}
	policyRules := []rbacv1.PolicyRule{}
	for _, permission := range rules.Builtins().Permissions() {
		if !clusterScoped && permission.Scope != "namespaced" {
			continue
		}
		policyRules = append(policyRules, rbacv1.PolicyRule{APIGroups: permission.APIGroups, Resources: permission.Resources, Verbs: permission.Verbs})
	}
	// Pod logs are fetched by -s and by -a --logs, outside pure analyzer rules.
	policyRules = append(policyRules, rbacv1.PolicyRule{APIGroups: []string{""}, Resources: []string{"pods/log"}, Verbs: []string{"get"}})
	if clusterScoped {
		policyRules = append(policyRules, rbacv1.PolicyRule{NonResourceURLs: []string{"/livez", "/livez/*", "/readyz", "/readyz/*"}, Verbs: []string{"get"}})
	}
	policyRules = normalize(policyRules)
	metadata := metav1.ObjectMeta{Name: "k8s-diagnose-reader", Labels: labels()}
	if !clusterScoped {
		metadata.Namespace = namespace
		return rbacv1.Role{TypeMeta: metav1.TypeMeta{APIVersion: rbacv1.SchemeGroupVersion.String(), Kind: kind}, ObjectMeta: metadata, Rules: policyRules}
	}
	return rbacv1.ClusterRole{TypeMeta: metav1.TypeMeta{APIVersion: rbacv1.SchemeGroupVersion.String(), Kind: kind}, ObjectMeta: metadata, Rules: policyRules}
}

func Connect(clusterScoped bool, namespace string) any {
	return additionalRole("k8s-diagnose-connect", clusterScoped, namespace, []rbacv1.PolicyRule{{APIGroups: []string{""}, Resources: []string{"pods/portforward"}, Verbs: []string{"create"}}})
}

func Debug(clusterScoped bool, namespace string) any {
	return additionalRole("k8s-diagnose-debug", clusterScoped, namespace, []rbacv1.PolicyRule{
		{APIGroups: []string{""}, Resources: []string{"pods"}, Verbs: []string{"create"}},
		{APIGroups: []string{""}, Resources: []string{"pods/ephemeralcontainers"}, Verbs: []string{"update"}},
	})
}

func additionalRole(name string, clusterScoped bool, namespace string, policyRules []rbacv1.PolicyRule) any {
	metadata := metav1.ObjectMeta{Name: name, Labels: labels()}
	if clusterScoped {
		return rbacv1.ClusterRole{TypeMeta: metav1.TypeMeta{APIVersion: rbacv1.SchemeGroupVersion.String(), Kind: "ClusterRole"}, ObjectMeta: metadata, Rules: policyRules}
	}
	metadata.Namespace = namespace
	return rbacv1.Role{TypeMeta: metav1.TypeMeta{APIVersion: rbacv1.SchemeGroupVersion.String(), Kind: "Role"}, ObjectMeta: metadata, Rules: policyRules}
}

func labels() map[string]string {
	return map[string]string{"app.kubernetes.io/name": "k8s-diagnose", "app.kubernetes.io/managed-by": "k8s-diagnose-rbac-generator"}
}

func normalize(values []rbacv1.PolicyRule) []rbacv1.PolicyRule {
	for index := range values {
		sort.Strings(values[index].APIGroups)
		sort.Strings(values[index].Resources)
		sort.Strings(values[index].Verbs)
		sort.Strings(values[index].NonResourceURLs)
	}
	sort.Slice(values, func(i, j int) bool {
		left := fmt.Sprint(values[i].APIGroups, values[i].Resources, values[i].NonResourceURLs, values[i].Verbs)
		right := fmt.Sprint(values[j].APIGroups, values[j].Resources, values[j].NonResourceURLs, values[j].Verbs)
		return left < right
	})
	return values
}

func Render(value any) ([]byte, error) {
	data, err := yaml.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("RBAC YAMLを生成できません: %w", err)
	}
	return append([]byte(generatedHeader), data...), nil
}

func Documents(namespace string) (map[string][]byte, error) {
	if problems := validation.IsDNS1123Label(namespace); len(problems) > 0 {
		return nil, fmt.Errorf("Namespace名が不正です: %s", problems[0])
	}
	values := map[string]any{
		"k8s-diagnose-role.yaml":                Reader(false, namespace),
		"k8s-diagnose-clusterrole.yaml":         Reader(true, namespace),
		"k8s-diagnose-connect-role.yaml":        Connect(false, namespace),
		"k8s-diagnose-connect-clusterrole.yaml": Connect(true, namespace),
		"k8s-diagnose-debug-role.yaml":          Debug(false, namespace),
		"k8s-diagnose-debug-clusterrole.yaml":   Debug(true, namespace),
	}
	result := map[string][]byte{}
	for name, value := range values {
		data, err := Render(value)
		if err != nil {
			return nil, err
		}
		result[name] = data
	}
	return result, nil
}

func Write(directory, namespace string, check bool) error {
	documents, err := Documents(namespace)
	if err != nil {
		return err
	}
	if info, err := os.Stat(directory); err != nil || !info.IsDir() {
		return fmt.Errorf("出力先ディレクトリがありません: %s", directory)
	}
	names := make([]string, 0, len(documents))
	for name := range documents {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(directory, name)
		if check {
			current, err := os.ReadFile(path) // #nosec G304 -- cmd/rbac explicitly selects the output directory to verify.
			if err != nil {
				return fmt.Errorf("RBAC雛形がありません: %s", path)
			}
			if !bytes.Equal(current, documents[name]) {
				return fmt.Errorf("RBAC雛形がルール定義と一致しません: %s", path)
			}
			continue
		}
		if err := report.WriteAtomic(path, documents[name]); err != nil {
			return err
		}
	}
	return nil
}
